### ISSUE TITLE
History audit migration (0175) causes psycopg2 SyntaxError on older versions of PostgreSQL

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#12095]
There have been reports of errors during the 174 > 175 migration on older versions of PostgreSQL. 

Ref:
- https://github.com/galaxyproject/galaxy/pull/11914#issuecomment-844297176 (and https://gitter.im/galaxyproject/Lobby?at=60a53ec5aefc5d044af8e266)
- https://github.com/galaxyproject/galaxy/pull/11914#issuecomment-854907830

**Comment by dannon** [comment]
(copied from my comment on the thread in question)

The first comment was fixed in https://github.com/galaxyproject/galaxy/pull/12079.

The second issue is that `ON CONFLICT` is only available in postgres 9.5+, and this instance was using 9.3.   The fastest fix for anyone affected might be to just update (9.5 came out in 2016, so hopefully it's available in whatever distro, but you never know).

A fix to support all 9.x postgres installs until we deprecate it (that will take someone doing the integration work and test) is here:  https://stackoverflow.com/questions/17267417/how-to-upsert-merge-insert-on-duplicate-update-in-postgresql

**Comment by nsoranzo** [comment]
@ic4f @dannon If my understanding is correct, the minimum supported version of PostgreSQL to use Galaxy 21.05 is now 9.5, right? I still cannot see that mentioned in the 21.05 release notes though (I was about to upgrade our institute server, which still uses 9.4).
