### ISSUE TITLE
Tool version sorting issue: Scanpy tools default to middle-tools

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#15580]
For some reason, when you select different Scanpy tools , they default to random versions in the middle of the list.

This has burned us in a few training sessions now - can someone please figure out why they aren't defaulting to the most recent?

![Screenshot 2023-02-14 at 15 59 37](https://user-images.githubusercontent.com/44605769/218807017-016a47e1-fc87-4e15-9a85-c7355def1bd1.png)
![Screenshot 2023-02-14 at 15 59 42](https://user-images.githubusercontent.com/44605769/218807010-6ab3d8eb-bc38-4c74-8a2e-a45368791158.png)

![Screenshot 2023-02-14 at 16 00 23](https://user-images.githubusercontent.com/44605769/218807000-c03ddc51-d1c4-410d-9184-2faa68f9839c.png)

**Comment by pcm32** [comment]
This is an issue with some unfortunate versioning issue with the formatting that one of us picked once (`<version>+<num>+galaxy<num2>`) which makes the standard python package that sorts versions dizzy. I have a PR almost ready to merge https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/pull/266 that should push newer versions of the tools with out the problematic pattern, which should put a newer version at the top.

**Comment by hexylena** [comment]
I think there was some discussion as well (@nsoranzo?) to maybe have a smarter sort that knows how to sort `+galaxy` versions, rather than relying solely on the package tools version comparison (but I couldn't find it.)

**Comment by pcm32** [comment]
Yes, we discussed this problem in a previous issue, but cannot find it. I'm testing my changes on that PR above to merge, hopefully that will put back the newest tool at the top.

**Comment by hexylena** [comment]
@mvdbeek is there a related issue or PR that closes this out in 23.0? Did I miss something?

**Comment by hexylena** [comment]
We can't? Wasn't there some discussion that we could, by augmenting the comparison if and only if `+galaxy` was included, to parse the right half of that as a number?

**Comment by mvdbeek** [comment]
We could do all sorts of fancy things, but there is an established convention, there is a fix that is easy enough (https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/pull/266), so I don't think we need to descend into something that I don't think is as easy as what you're suggesting, however if someone wants to implement this and prove that it doesn't breaking sorting for any existing tool than that would obviously be fantastic and welcome. In the meantime I don't think we should track this as an open issue.

**Comment by hexylena** [comment]
I neither said, nor implied, "easy" in any of my comments. Only that I remembered some discussion and I was keen to re-discover said discussion in case it had additional context I was missing.

**Comment by mvdbeek** [comment]
And I would like to close this issue as wontfix and set realistic expectations.

**Comment by hexylena** [comment]
Yes, that's fine, I didn't reopen or suggest that we should. Again, just trying to find the conversation I remember.

**Comment by davelopez** [comment]
Might be this one? https://github.com/galaxyproject/galaxy/issues/15071

**Comment by hexylena** [comment]
Thank you @davelopez that looks like it!

**Comment by hexylena** [comment]
I mis-remembered it being focused on the general case of `+galaxy`, rather than this specific EBI tool case with the superfluous `+`, since I have tools that go up to `+galaxy10` experiencing this issue.

**Comment by bgruening** [comment]
@hexylena I'm happy to "hide" the tools that are causing this to bring the linage back into shape.

**Comment by pcm32** [comment]
Can we keep the conflicting tools visible until I push the newer version to the toolshed and that gets installed in eu? I wasn't aware that `+galaxy10` would be conflictive as well, I was using that on my PR to fix this :-( .

**Comment by hexylena** [comment]
@pcm32 it sorts as text, you can see it on the circos tools. It's a bit unfortunate since it presents the same way.

![image](https://user-images.githubusercontent.com/458683/219006376-6d0cd2dd-6ed0-45f9-b66e-5676746d9f76.png)

You can try `+galaxy91`, perhaps that sorts about `+galaxy9`

**Comment by nsoranzo** [comment]
I am planning to (find the time to) fix +galaxy10, but not the +3+galaxyX , there is already a partial fix PR from Nate.

**Comment by hexylena** [comment]
fantastic @nsoranzo! Oh, and wow #13570 was also citing directly circos, brilliant.

**Comment by pcm32** [comment]
I have merged the tools with the version naming fix and they have been pushed to the toolshed, so now it should only be a matter for the galaxy.eu CI job that installs tools to get those updated @nomadscientist . Hopefully this should put those tools at the top.

**Comment by nomadscientist** [comment]
@pcm32 so currently today, it's still not on top 
<img width="1056" alt="Screenshot 2023-02-21 at 10 37 42" src="https://user-images.githubusercontent.com/44605769/220322159-d0edd5c8-4185-41b7-ad86-57506f41c075.png">
And I can also still confirm that Scanpy is defaulting to the middle tools when you click it
I'm not 100% following this, has this problem moved to a different issue link? Otherwise I'd say it's not closed?

**Comment by mvdbeek** [comment]
This is the development repo for Galaxy, this is a tool issue. I can install the update on .org, only then will it appear there.

**Comment by mvdbeek** [comment]
It's updated on usegalaxy.org, I think .eu runs tool updates in the weekend. 
<img width="286" alt="Screenshot 2023-02-21 at 12 13 37" src="https://user-images.githubusercontent.com/6804901/220330045-68fa996a-86e8-433c-99d2-7ba5458dd283.png">

**Comment by nomadscientist** [comment]
WOOOOO! Awesome thanks!

**Comment by pcm32** [comment]
I did push these tools last week (Wednesday or si probably), so they should be picked up by galaxy.eu, unless there was some issue on the CI this past weekend?

**Comment by nomadscientist** [comment]
OK I just checked out .eu server today, and it still is automatically going for the older tools
<img width="1153" alt="Screenshot 2023-03-01 at 13 59 24" src="https://user-images.githubusercontent.com/44605769/222162897-9e66f71c-6015-4ba0-81da-66d58b26e91e.png">

**Comment by nomadscientist** [comment]
@mtekman do you happen to know why the tools are sticking to the old versions? Did you have to anchor that for a course at one point because newer tools were failing?

**Comment by mvdbeek** [comment]
That makes sense as .eu hasn't installed the new version

**Comment by mvdbeek** [comment]
I checked out the source on usegalaxy.eu:

![Screenshot 2023-03-01 at 16 34 58](https://user-images.githubusercontent.com/6804901/222187306-5030fbd7-f683-4539-b580-f3c548c84fc5.png)

the side panel is explicitly point at the old version, I think a restart might be enough to fix that ?

ping @bgruening

**Comment by bgruening** [comment]
The service is restarted every day, so I doubt a restart fixes it. I can hide older tools with strange version numbers if you like.

**Comment by bgruening** [comment]
@pcm32 we updated over the weekend, can you please recheck? If it still does not work, please let me know which versions I should hide.

**Comment by nomadscientist** [comment]
IT WORKS! AHHHHH YAYYYY!

**Comment by bgruening** [comment]
Awesome, one tab less in my browser. Thanks, everyone.

**Comment by nomadscientist** [comment]
OK sorry team, but new related problem - so the tutorial links to the `1.8.1+galaxy0` tool on Github
<img width="330" alt="Screenshot 2023-04-20 at 16 26 01" src="https://user-images.githubusercontent.com/44605769/233413824-0aba5bb7-c6a1-4af8-a13b-7d4ce09425f2.png">

However, when you actually go to click the button, it takes you to the most recent tool (1.8.1+galaxy9). This is going to be a problem as the tutorial is only verified on the tools we test on it, so if it's not linking to the right tool version, this is going to burn us later. Any ideas why this is happening?

**Comment by nomadscientist** [comment]
@bgruening @mvdbeek @pcm32 @hexylena  
Hi folks, do you have any thoughts on this related issue? When you select the tool in Tutorial mode, it nevertheless defaults to the newest tool, meaning it's still over-riding the links in Tutorial mode (which aren't necessarily the newest, and certainly won't be over time).

**Comment by hexylena** [comment]
if it's getting the wrong version in tutorial mode, then that's a different bug. we should see what's happening there. do you have a specific hands on box you can link me to?

**Comment by nomadscientist** [comment]
Scanpy PlotEmbed does this; Scanpy RunPCA, etc. etc. I think it's all the Scanpy tools. You can see it a lot here: https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_basic-pipeline/tutorial.html

**Comment by mvdbeek** [comment]
Could you verify this against the latest versions ? I would assume that the majority of users are simply following along the instructions ... if you have more than one screen you're probably not using the overlay mode.

**Comment by hexylena** [comment]
we should probably add a flag where tool versions are super key, and then expose the version more visibly for those.

**Comment by nomadscientist** [comment]
Agreed - have you checked the buttons? Do you happen to know why the tutorial-mode isn't working to let us select the actual tutorial linked tools?

**Comment by hexylena** [comment]
@nomadscientist I'm testing this morning, it appears to be functional on EU at least. Using your two examples there, runPCA and the subsequent tool in the "Filter..." single cell tutorial, both seem to load the requested tool version

**Comment by nomadscientist** [comment]
hang onto your hat because I think Julia was an angel and updated the tool
versions in the tutorials to match

**Comment by nomadscientist** [comment]
Oh no! It is fixed! Oh boy!
