### ISSUE TITLE
galaxy fails to run on Centos 6: sha256sum --strict not supported

### ISSUE THREAD

**Issue by ghost** [galaxyproject/galaxy#1563]
Reported against ce3f2b9.

Galaxy fails to run on CentOS 6 as the version of sha256sum bundled with this distribution does not support the --strict flag.

To repeat, on CentOS 6:

``` console
 # git clone https://github.com/galaxyproject/galaxy.git 
 # cd galaxy
 # sh run.sh
```

 ...resulting in the error when running scripts/common_startup.sh (line 98):

```
sha256sum: unrecognized option '--strict'
```

**Comment by ghost** [comment]
Hi I get the same error . Any timeline when this should be resolved?.

**Comment by lewu** [comment]
This is how I got around this issue under rhel 6. 
(1) go to galaxy_installation_dir/scripts
(2) modify common_startup.sh line 103 as "echo "$vsha  $vsrc" | sha256sum -c". Please note that, there must be 2 space between $vsha and $vsr.

**Comment by nsoranzo** [comment]
:+1:

**Comment by ghost** [comment]
@lewu That would make the script run, but would not stop it running if the checksum failed, which is the intention of the change.

**Comment by nsoranzo** [comment]
Another workaround may be to install `python-virtualenv` rpm (if you're using the stock python 2.6).

**Comment by natefoo** [comment]
Sorry for the delay, I'll get this fixed today.

`--strict` [was introduced in coreutils 8.13](http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=blob;f=NEWS;h=51958aea265afb66ce443fa6436a26b399b86cfa;hb=HEAD#l1148), RHEL 6 uses 8.4. We can just use the python method in the `else` block if the version of coreutils < 8.13 (or we could just always use the python version).

**Comment by yhoogstrate** [comment]
> we could just always use the python version

That is the cleanest solution I think.

**Comment by natefoo** [comment]
Fixed in #1668.

**Comment by methylome** [comment]
Hi Nate,
Galaxy still failed on CentOS 5.11.
...
Activating virtualenv at .venv
Traceback (most recent call last):
  File "./scripts/paster.py", line 27, in <module>
    serve.run()
  File "/home/galaxydev/lib/galaxy/util/pastescript/serve.py", line 1061, in run
    invoke(command, command_name, options, args[1:])
  File "/home/galaxydev/lib/galaxy/util/pastescript/serve.py", line 1067, in invoke
    exit_code = runner.run(args)
  File "/home/galaxydev/lib/galaxy/util/pastescript/serve.py", line 223, in run
    result = self.command()
  File "/home/galaxydev/lib/galaxy/util/pastescript/serve.py", line 639, in command
    app = loadapp( app_spec, name=app_name, relative_to=base, global_conf=vars)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 295, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 319, in loadobj
    global_conf=global_conf)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 344, in loadcontext
    global_conf=global_conf)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 368, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 506, in get_context
    section)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 565, in _context_from_explicit
    value = import_string(found_expr)
  File "/home/galaxydev/lib/galaxy/util/pastescript/loadwsgi.py", line 125, in import_string
    return pkg_resources.EntryPoint.parse("x=" + s).load(False)
  File "/home/galaxydev/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/galaxydev/.venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/home/galaxydev/lib/galaxy/web/buildapp.py", line 5, in <module>
    from galaxy.webapps.galaxy.buildapp import app_factory
  File "/home/galaxydev/lib/galaxy/webapps/galaxy/buildapp.py", line 15, in <module>
    import galaxy.app
  File "/home/galaxydev/lib/galaxy/app.py", line 6, in <module>
    from galaxy import config, jobs
  File "/home/galaxydev/lib/galaxy/jobs/**init**.py", line 19, in <module>
    from galaxy import model, util
  File "/home/galaxydev/lib/galaxy/model/**init**.py", line 31, in <module>
    import galaxy.datatypes.registry
  File "/home/galaxydev/lib/galaxy/datatypes/registry.py", line 9, in <module>
    import tabular
  File "/home/galaxydev/lib/galaxy/datatypes/tabular.py", line 18, in <module>
    from galaxy.datatypes.sniff import get_headers
  File "/home/galaxydev/lib/galaxy/datatypes/sniff.py", line 19, in <module>
    from galaxy.datatypes.binary import Binary
  File "/home/galaxydev/lib/galaxy/datatypes/binary.py", line 13, in <module>
    import pysam
  File "/home/galaxydev/.venv/lib/python2.7/site-packages/pysam/**init**.py", line 1, in <module>
    from pysam.libchtslib import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /home/galaxydev/.venv/lib/python2.7/site-packages/pysam/libchtslib.so)

Thanks,
Justin.

**Comment by natefoo** [comment]
@methylome Our dependencies for version 16.01 are built on Debian 6, which uses a newer version of GLIBC. With this release, we are not supporting CentOS 5.

**Comment by methylome** [comment]
Hi Nate,

If CentOS 5 won't be supported in the future version, it is better to install CentOS 6. Can you instruct me how to reinstall all tools in batch? Is there anyway to manage tools on the command line or in batch? It's painful to add tools one by one.

Thanks,
Justin.

**Comment by mvdbeek** [comment]
Hi @methylome,

I'd recommend https://raw.githubusercontent.com/galaxyproject/ansible-galaxy-tools/master/files/install_tool_shed_tools.py.
You can get your currently installed tools with this script:
https://raw.githubusercontent.com/ARTbio/tools-artbio/master/helper_scripts/get_tool_yml_from_gi.py 

If I was doing this, I would first run this against your current server

```
python get_tool_yml_from_gi.py -a "your admin api key", -g "your galaxy instance url" -o tool_list.yml -skip_id
```

This will produce a list of all currently installed tools and their tool_panel_section.

Then install your new galaxy, and run

```
python install_tool_shed_tools.py -a "your new admin api key" -g "your new galaxy instance url" -t tool_list.yml
```

You'll need to have bioblend installed (`pip install bioblend`)

**Comment by methylome** [comment]
Hi @mvdbeek,

Thanks a lot. I've tried get_tool_yml_from_gi.py, but got the following errors:
Traceback (most recent call last):
  File "./get_tool_yml_from_gi.py", line 261, in <module>
    skip_tool_panel_section_name=options.skip_tool_panel_name)
  File "./get_tool_yml_from_gi.py", line 35, in **init**
    self.tool_panel_list_filtered = self.filter_tool_panel_list()
  File "./get_tool_yml_from_gi.py", line 59, in filter_tool_panel_list
    for tool in section["elems"]:
KeyError: 'elems'

I think this is caused by the value of section:
{u'panel_section_name': u'', u'config_file': u'/home/galaxy/dev/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/samtools_mpileup/973fea5b4bdf/samtools_mpileup/samtools_mpileup.xml', u'description': u'SNP and indel caller', u'labels': [], u'panel_section_id': u'', u'version': u'0.0.3', u'link': u'/devgalaxy/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fsamtools_mpileup%2Fsamtools_mpileup%2F0.0.3', u'target': u'galaxy_main', u'min_width': -1, u'model_class': u'Tool', u'id': u'toolshed.g2.bx.psu.edu/repos/devteam/samtools_mpileup/samtools_mpileup/0.0.3', u'name': u'MPileup'}

**Comment by mvdbeek** [comment]
@methylome interesting. Is this is a tool installed outside of any tool panel section?
Wait ... are you sure you're using an admin api key?
I tested the script also with tools outside of tool panel sections ... it does fail without an admin api key.

**Comment by mvdbeek** [comment]
@methylome can you try again with [this](https://raw.githubusercontent.com/ARTbio/tools-artbio/get_tool_debug/helper_scripts/get_tool_yml_from_gi.py) script ?
I am skipping and printing sections that have no "elems" key.
I would be curious to look at the output.

**Comment by methylome** [comment]
No, it has been installed on Galaxy. The output of the new script is
This section had no "elems" key:
%s
print section gives:
{u'panel_section_name': u'', u'config_file': u'/home/galaxy/dev/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/samtools_mpileup/973fea5b4bdf/samtools_mpileup/samtools_mpileup.xml', u'description': u'SNP and indel caller', u'labels': [], u'panel_section_id': u'', u'version': u'0.0.3', u'link': u'/devgalaxy/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fsamtools_mpileup%2Fsamtools_mpileup%2F0.0.3', u'target': u'galaxy_main', u'min_width': -1, u'model_class': u'Tool', u'id': u'toolshed.g2.bx.psu.edu/repos/devteam/samtools_mpileup/samtools_mpileup/0.0.3', u'name': u'MPileup'}

Thanks,
Justin

**Comment by methylome** [comment]
The output file has 
- name: samtools_mpileup
  owner: devteam
  revisions:
  - 973fea5b4bdf
  - aa0ef6f0ee89
    tool_panel_section_label: 'NGS: SAM/BAM manipulation'
    tool_shed_url: https://toolshed.g2.bx.psu.edu/
    I believe it's the same as the entry which the error occured. I can see on "Installed tool shed repositories" two sam_mpileup entries of which reivisions are 973fea5b4bdf and aa0ef6f0ee89.

**Comment by mvdbeek** [comment]
If all of the remaining tools are in the output file, I think you can go ahead and try to install them on your new galaxy instance.
In the meantime I will improve the script to handle this situation.

**Comment by methylome** [comment]
I think the output is incomplete because there are 232 tools on the web interface but the output file has 132 names and 144 revisions. I can't see all_cufflinks_tool_suite in the output file. Is this correct?

**Comment by mvdbeek** [comment]
@methylome I opened an issue over at the repo where this script lives, since it's not about sha256sum --strict anymore. In short, we are discarding tool_suites, since we can't determine where they have been installed. Instead we install all tools that were defined by a suite. Also we are not listing package_\* entries, since they are installed with the tools. Yet, I would be interested in seeing if the script misses something else.
