### ISSUE TITLE
BUG: Changing values in workflow select boxes breaks some workflows

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2944]
Since 16.07, I've noticed a few things:
1. In some cases, changing the input file will cause various parameters in the workflow to revert to default settings. See http://imgur.com/a/WMjde for an example.
2. In all cases, when the value of a dropdown is changed, the entire form jumps back to the top. In other words, the window resets as scrolled all the way back to the top. At the very least, this is annoying, though I suspect it could be causing other issues. Perhaps not returning `false` at the end of the `onclick` method?

**Comment by guerler** [comment]
The first issue seems to be related to: https://github.com/galaxyproject/galaxy/pull/2920. The second one is a consequence of refreshing the whole page. It is solved in the upcoming run workflow form revision.

**Comment by lparsons** [comment]
I updated to the latest 16.07 but I'm still seeing this bug. Has the fix been merged yet? Somehow I thought so, but perhaps I'm missing something (or there is another issue).

**Comment by guerler** [comment]
The refresh and rescrolling issue for non-dataset selectores is related to old workflow run form still active in 16.07.

**Comment by hexylena** [comment]
We've swapped over to the new WF interface so hopefully these bugs are fixed now :)
