### ISSUE TITLE
Uniprot tool has a dependency problem at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3721]
There is no command-line to share (not in the bug report nor on the info page in the UI.

But this is an error example:

> Detailed Job Information
> 
> Job environment and execution information is available at the job Info Page.
> Job ID	XX (XX)
> Tool ID	toolshed.g2.bx.psu.edu/repos/bgruening/uniprot_rest_interface/uniprot/0.1
> Tool Version	0.1
> Job PID or DRM id	None
> Job Tool Version	None
> Job Execution and Failure Information
> 
> Command Line
> 
> None
> stderr
> 
> 
> stdout
> 
> 
> Job Information
> 
> cannot find 'frtoom' while searching for 'tool.frtoom.category_TO'
> Job Traceback
> 
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 967, in prepare
>     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 454, in build
>     raise e
> NotFound: cannot find 'frtoom' while searching for 'tool.frtoom.category_TO'

**Comment by blankenberg** [comment]
most likely fixed in the latest version of the tool in the toolshed

ping @bgruening

**Comment by ghost** [comment]
Hi! Unfortunately, the error is still occurring @blankenberg @bgruening

**Comment by blankenberg** [comment]
@martenson Need to install new version from toolshed.

**Comment by martenson** [comment]
@blankenberg You can do this too! :)

**Comment by martenson** [comment]
uniprot has been updated, please re-test @galaxyproject/guac

**Comment by jennaj** [comment]
I'll put this into the retest queue. Thanks!

**Comment by martenson** [comment]
ping @jennaj - is this ok?

**Comment by jennaj** [comment]
The issue above is fixed but not all retrieval combos work. That is expected. Some return a null value (map) or no output (if from Uniprot but IDs not in UniProt format - I tested with Ensembl). 

One combo did give an error (instead of null/empty data) when the IDs are in a multi-column tab file but produced empty results (expected) when the column is isolated. Corner case and incorrect data mapping anyway so think Ok to skip trying to address it. The error was related to the uniprot api having trouble parsing the extra content and is isolated to that particular option combo (that I could find - didn't test every single possible input/option set (are ~50). 

Punch line: Not much information is given back to the user when there is one of these usage problems, but the tool does so much, it doesn't seem practical to trap all with a "why exactly this is wrong and this is what to do" warning. The inputs simply much be a match for the action. 

I have all this in a test history if we ever want to go back to it. Very few users have reported problems with the tool since the dependency fix was made, so low priority.

I wanted to test in `17.09` just to make sure these were not a Galaxy issue before closing out. That's done now, so closing!
