### ISSUE TITLE
Problems with job handling submitted by DRMAA runner when using uWSGI configuration

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#6261]
Hello all,

I'm doing an upgrade to v18.05 and I'm having some troubles when running jobs .
First of all, it all works fine when using the Paste server.

The problem is when launching Galaxy using uWSGI: if I don't use a job_conf.xml it works ok and jobs are run locally but, when I try to configure the DRMAA runner, the worker does all the work up to job submission to the cluster but never changes the status to running and does not handles the output. So, in the web interface it is shown in gray, and in the db table job_state_history the job last status is queued. 

Here is the output from the log:

```
galaxy.tools.actions INFO 2018-06-01 11:46:24,884 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Handled output named output_quant for tool salmon (116.123 ms)
galaxy.tools.actions INFO 2018-06-01 11:46:24,959 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Handled output named log for tool salmon (74.800 ms)
galaxy.tools.actions DEBUG 2018-06-01 11:46:24,959 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Dataset output filter failed: name 'geneMap' is not defined
galaxy.tools.actions INFO 2018-06-01 11:46:25,008 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Handled output named output_gene_quant for tool salmon (49.552 ms)
galaxy.tools.actions INFO 2018-06-01 11:46:25,014 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Added output datasets to history (5.781 ms)
galaxy.tools.actions INFO 2018-06-01 11:46:25,031 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Verified access to datasets for Job[unflushed,tool_id=salmon] (6.907 ms)
galaxy.tools.actions INFO 2018-06-01 11:46:25,032 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Setup for job Job[unflushed,tool_id=salmon] complete, ready to flush (17.167 ms)
galaxy.tools.actions INFO 2018-06-01 11:46:25,077 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Flushed transaction for job Job[id=98,tool_id=salmon] (45.700 ms)
galaxy.tools.execute DEBUG 2018-06-01 11:46:25,078 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Tool [salmon] created job [98] (344.740 ms)
galaxy.tools.execute DEBUG 2018-06-01 11:46:25,090 [p:73520,w:2,m:0] [uWSGIWorker2Core0] Executed 1 job(s) for tool salmon request: (644.343 ms)

galaxy.jobs DEBUG 2018-06-01 11:46:25,808 [p:73520,w:2,m:0] [JobHandlerQueue.monitor_thread] (98) Working directory for job is: /galaxypsb/scratch_test/database/jwd/000/98
galaxy.jobs.handler DEBUG 2018-06-01 11:46:25,848 [p:73520,w:2,m:0] [JobHandlerQueue.monitor_thread] (98) Dispatching to drmaa runner
galaxy.jobs DEBUG 2018-06-01 11:46:25,922 [p:73520,w:2,m:0] [JobHandlerQueue.monitor_thread] (98) Persisting job destination (destination id: cluster_16G)
galaxy.jobs.runners DEBUG 2018-06-01 11:46:25,939 [p:73520,w:2,m:0] [JobHandlerQueue.monitor_thread] Job [98] queued (90.983 ms)
galaxy.jobs.handler INFO 2018-06-01 11:46:25,954 [p:73520,w:2,m:0] [JobHandlerQueue.monitor_thread] (98) Job dispatched
galaxy.util.object_wrapper WARNING 2018-06-01 11:46:26,098 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] Unable to create dynamic subclass for <class 'galaxy.util.none_like.NoneDataset'>, None: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
galaxy.tools.deps DEBUG 2018-06-01 11:46:26,140 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] Using dependency salmon version 0.7.2 of type conda
galaxy.jobs.command_factory INFO 2018-06-01 11:46:26,179 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] Built script [/ .....]
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 11:46:26,865 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) submitting file /galaxypsb/scratch_test/database/jwd/000/98/galaxy_98.sh
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 11:46:26,865 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) native specification is: -S /bin/bash -l h_vmem=16G
galaxy.jobs DEBUG 2018-06-01 11:46:26,866 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) Changing ownership of working directory with: sudo /galaxypsb/src_test/scripts/external_chown_script.csh /galaxypsb/scratch_test/database/jwd/000/98 igegu 236
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 11:46:27,059 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) submitting with credentials: igegu [uid: 1181]
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 11:46:27,099 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) Job script for external submission is: /galaxypsb/scratch_test/database/pbs/98.jt_json
galaxy.jobs.runners.drmaa INFO 2018-06-01 11:46:27,100 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] Running command ['sudo', '/galaxypsb/src_test/scripts/drmaa_external_runner.csh', '--assign_all_groups', '1181', '/galaxypsb/scratch_test/database/pbs/98.jt_json']
galaxy.jobs.runners.drmaa INFO 2018-06-01 11:46:27,273 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) queued as 2870432
galaxy.jobs DEBUG 2018-06-01 11:46:27,273 [p:73520,w:2,m:0] [DRMAARunner.work_thread-0] (98) Persisting job destination (destination id: cluster_16G)
```

After this, I can see the job running on the cluster, all the output is correctly generated in the corresponding job dir and job ends fine, but no handler processes this output.

In the case of using Paste, after these steps it prints:
```
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 12:03:06,987 (92/2870443) state change: job is queued and active
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 12:03:08,240 (92/2870443) state change: job is running

galaxy.jobs.runners.drmaa WARNING 2018-06-01 12:14:19,438 (99/2870443) unable to check job status because of InvalidJobException exception for 1 consecutive tries: code 18: The job specified by the 'jobid' does not exist.
galaxy.jobs.runners.drmaa WARNING 2018-06-01 12:14:19,438 (99/2870443) job will now be finished OK
```

I'm using a simple job_conf.xml to test this (use the same when launching with Paste and uWSGI):

`<?xml version="1.0"?>

    <plugins>
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="1"/>
        <plugin id="drmaa" type="runner" load="galaxy.jobs.runners.drmaa:DRMAAJobRunner"/>
    </plugins>

    <destinations default="cluster_16G">
        
        <destination id="local" runner="local"/>
       <destination id="cluster_16G" runner="drmaa">
            <param id="nativeSpecification">-S /bin/bash -l h_vmem=16G</param>
        </destination>

    </destinations>

`
 
Cheers,
Ignacio

**Comment by mvdbeek** [comment]
Do you have the possibility to test this without `drmaa_external_runjob_script`, `drmaa_external_killjob_script`, `external_chown_script`  and `real_system_username` ? We have seen reports like this before, but haven't really been able to figure out what is going on here

**Comment by ieguinoa** [comment]
If I remove those options it reaches the same point (submission) but the job never gets submitted to the queue (I don't see it running in the cluster):

galaxy.jobs.runners.drmaa DEBUG 2018-06-01 14:09:50,222 [p:75271,w:2,m:0] [DRMAARunner.work_thread-0] (101) submitting file /galaxypsb/scratch_test/database/jwd/000/101/galaxy_101.sh
galaxy.jobs.runners.drmaa DEBUG 2018-06-01 14:09:50,222 [p:75271,w:2,m:0] [DRMAARunner.work_thread-0] (101) native specification is: -S /bin/bash -l h_vmem=16G

But I'm not sure if, in this case, there may be some other error occurring here that is not being shown.

In the db it is shown as queued

**Comment by mvdbeek** [comment]
I have an idea what this could be. Can you check in the database if you have a external id assigned to Job 98 ?

**Comment by mvdbeek** [comment]
You can also see that in the admin panel, manage jobs, last column (PID/Cluster ID)

**Comment by ieguinoa** [comment]
Yes, job 98 is shown as unfinished and the external id is there, same that is printed in the log: queued as 2870432

**Comment by mvdbeek** [comment]
Can you also check that the job ids are correct and that you can check these as the galaxy user ?

```
galaxy.jobs.runners.drmaa WARNING 2018-06-01 12:14:19,438 (99/2870443) unable to check job status because of InvalidJobException exception for 1 consecutive tries: code 18: The job specified by the 'jobid' does not exist.
```

Doesn't look correct either

**Comment by ieguinoa** [comment]
job ids are ok and I can query them using the binary inside sge package from the Galaxy server with the galaxy user. 
About the InvalidJobException exception, as far as I can tell it, given that Galaxy handler queries for information about the job and the possible status are running or does not exists then this is expected based on the behaviour of sge, once it goes as invalid after being on OK it means it somehow finished. Also I assumed the communication with the queuing system was working fine because it is the same for submitting, killing, or querying for job status.

**Comment by mvdbeek** [comment]
that makes some sense. so which of the setups are you trying to achieve ? Is it https://docs.galaxyproject.org/en/master/admin/scaling.html?highlight=mule#uwsgi-mule-job-handling ?

**Comment by ieguinoa** [comment]
I was actually going for the uWSGI all-in-one job handling, I thought that would be the easiest

**Comment by mvdbeek** [comment]
So there's no handler defined in your job_conf.xml file ?

**Comment by ieguinoa** [comment]
Exactly.
Something else related with that, if I do define a handler like this:
`    <handlers>
        <handler id="main"/>
    </handlers>`
Then it won't submit at all when using uWSGI (I guess the id must be wrong or something), but it does work ok if I use Paste.

**Comment by mvdbeek** [comment]
That makes sense, you shouldn't have a handlers section defined if uwsgi is supposed to act as job handler.

**Comment by marijazmf** [comment]
@mvdbeek , @ieguinoa ,
Is there any solution for this issue? I went into the same problem :(

**Comment by mvdbeek** [comment]
Could you answer which deployment you want to achieve?. You'll probably want to follow the uwsgi + mules strategy described at https://docs.galaxyproject.org/en/master/admin/scaling.html?highlight=mule#uwsgi-mule-job-handling. If you do that please make sure that there is no `<handlers>` section in your job_conf.xml. if that still doesn't work it'd be great if you could share your job_conf.xml, the log around the time that you submit a new job, and how you start Galaxy.

**Comment by marijazmf** [comment]
Hi @mvdbeek ,
Yes, I am using uWSGI + Mule job handling. My galaxy.yml file looks like this:
```
uwsgi:
  socket: 127.0.0.1:4001
  http: 0.0.0.0:8080
  buffer-size: 16384
  processes: 4
  threads: 8
  offload-threads: 2
  static-map: /static/style=static/style/blue
  static-map: /static=static
  master: true
  virtualenv: .venv
  pythonpath: lib
  module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
  thunder-lock: true
  die-on-term: true
  hook-master-start: unix_signal:2 gracefully_kill_them_all
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true  
  #mule: lib/galaxy/main.py
  #mule: lib/galaxy/main.py
  #mule: lib/galaxy/main.py
  #farm: job-handlers:1,2,3
```
I had to comment out all mules, because I had threading issue I addressed [here](https://github.com/galaxyproject/galaxy/issues/6362).

job_conf.xml looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<job_conf>
   <plugins workers="4">
      <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" />
      <plugin id="slurm" type="runner" load="galaxy.jobs.runners.slurm:SlurmJobRunner">
         <param id="drmaa_library_path">/usr/lib/slurm-drmaa/lib/libdrmaa.so.1</param>
      </plugin>
   </plugins>
   <destinations default="debug">
      <destination id="debug" runner="slurm">
         <param id="embed_metadata_in_job">False</param>
         <param id="nativeSpecification">-p debug -n 10</param>
      </destination>
      <destination id="local" runner="local">
         <param id="local_slots">5</param>
      </destination>
   </destinations>
</job_conf>
```
And I am using supervisor to run Galaxy:
```

[program:galaxy_web]
command         = /home/galaxy/galaxy/.venv/bin/uwsgi --logto /home/galaxy/galaxy/log_files/uwsgi.log --yaml /home/galaxy/galaxy/config/galaxy.yml
directory       = /home/galaxy/galaxy
umask           = 022
autostart       = true
autorestart     = true
startsecs       = 10
user            = galaxy
numprocs        = 1
stopsignal      = INT
startretries    = 15
```
I hope this will help to find the problem.
Thanks,
Marija

**Comment by mvdbeek** [comment]
You definitely need to uncomment the mules as they are going to handle the jobs. I would decrease threads to 1 and see if you can start Galaxy. If that doesn't work, can you post the startup log?

**Comment by marijazmf** [comment]
Thanks for advice. I did that, but unfortunately I have the same problem:

```
galaxy.tools.toolbox.base ERROR 2018-07-25 13:27:33,893 [p:20196,w:0,m:2] [MainThread] Error reading tool from path: toolshed.g2.bx.psu.edu/repos/crs4/prokka/eaee459f3d69/prokka/prokka.xml
Traceback (most recent call last):
  File "lib/galaxy/tools/toolbox/base.py", line 565, in _load_tool_tag_set
    tool = self.load_tool(concrete_path, guid=guid, repository_id=repository_id, use_cached=False)
  File "lib/galaxy/tools/toolbox/base.py", line 758, in load_tool
    self._tool_watcher.watch_file(config_file, tool.id)
  File "lib/galaxy/tools/toolbox/watcher.py", line 198, in watch_file
    self.monitor(tool_dir)
  File "lib/galaxy/tools/toolbox/watcher.py", line 190, in monitor
    self.observer.schedule(self.event_handler, dir, recursive=False)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 293, in schedule
    emitter.start()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/watchdog/utils/__init__.py", line 111, in start
    self.on_thread_start()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/watchdog/observers/inotify_buffer.py", line 36, in __init__
    self.start()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/watchdog/utils/__init__.py", line 113, in start
    threading.Thread.start(self)
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

```

**Comment by mvdbeek** [comment]
Can you reduce processes to 1 as well? If that doesn't work you can set watch_tools: false in galaxy.yml and see if you get any further?

**Comment by marijazmf** [comment]
I changed those parameters to:
  processes: 2
  threads: 1
  offload-threads: 1
and it seems like it works now.
Thanks for your help!
Best,
Marija

**Comment by mvdbeek** [comment]
Great! You can probably increase the threads now to around 4, I think this was also the recommended setting for production systems.

**Comment by ooobik** [comment]
I had the same problem before - I got the solution through the galaxyproject gitter. ([link to convo, scroll upwards](https://gitter.im/galaxyproject/Lobby?at=5afeceba2df44c2d063a6d13)). Basically for now it can be solved by turning off the uwsgi master.

**Comment by ieguinoa** [comment]
I'm afraid this does not solve the problem in my case. I had the master:False (default) and also tested with true but this is not solved in any case. Still, the jobs get submitted to the cluster, they run ok but the result is never 'picked up' by Galaxy.

**Comment by mvdbeek** [comment]
@ieguinoa there's a fairly good chance we fixed this problem in https://github.com/galaxyproject/galaxy/pull/6836, if not do let us know.

**Comment by ieguinoa** [comment]
Hi @mvdbeek 
Thanks for the follow up.

I tried these changes but the problem persists. Althoguh I saw something extra showing up on the logs:

galaxy.jobs.runners.drmaa WARNING 2018-10-12 17:48:10,244 [p:60970,w:1,m:0] [DRMAARunner.monitor_thread] (90/2870124) unable to communicate with DRM: code 2: unable to send message to qmaster using port 6444 on host "chione": got send timeout
galaxy.jobs.runners.drmaa WARNING 2018-10-12 17:48:10,244 [p:60973,w:2,m:0] [DRMAARunner.monitor_thread] (212/3758670) unable to communicate with DRM: code 2: unable to send message to qmaster using port 6444 on host "chione": got send timeout

So the reason why this solution is not working could be something particular for my setup. I'm just writing this to let you know of this new msg but I will check this with the server admin in charge of chione, which is the queueing server and will keep you updated.

thanks again for your help.
Ignacio

**Comment by mvdbeek** [comment]
yeah, that looks like some progress, let us know if there is something we can do to help you out.

**Comment by wyan-galaxy** [comment]
I had similar issue with our local installed galaxy release 16.01.  We used galaxy.ini and job_conf.xml for the configuration.    After galaxy was restarted, it seems everything worked well, jobs got queued and run in the sge cluster.  However, the issue came out when the galaxy was in idle for a while (hrs or so).  The jobs still can be submitted and distributed to sge and run in cluster, but the galaxy can not update the job status in its web interface (the job status stayed in gray).  The job status would be picked up after we restarted the galaxy.   When the issue occurred, the paster log file recorded "unable to communicate with DRM: code 2: Requested session "5" does not exist".  I thought it might be something related with time-out, but I couldn't find out whether there is a parameter setting for it.  
Thank you for your help!

Jane
