### ISSUE TITLE
sniffing of xlsx file as blastxml

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6849]
reported on galaxy-dev, example file: [Book1.xlsx](https://github.com/galaxyproject/galaxy/files/2465937/Book1.xlsx)
![screenshot 2018-10-10 14 18 04](https://user-images.githubusercontent.com/1814954/46757169-6156b300-cc97-11e8-83b7-6baf56d6a69c.png)

**Comment by mvdbeek** [comment]
On top of https://github.com/galaxyproject/galaxy/pull/6867 which should fix the issue it also looks like the blastxml sniffer on usegalaxy.org is a bit overeager, on my dev instance this is being sniffed as a regular xml datatype. Which is weird, since we ship the blastxml datatype. Any chance that somehow a tool shed installed datatype somehow interfered here ? They shouldn't, but might be worth checking.

Or maybe main is using a non-default sniff order ?

**Comment by peterjc** [comment]
As per https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/blast.py#L64 the BLAST XML sniffer should be looking for files starting as follows (allowing for white space):

```xml
<?xml version="1.0"?>':
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
```

or,

```xml
<?xml version="1.0"?>':
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "NCBI_BlastOutput.dtd">
<BlastOutput>
```

This has not diverged meaningfully from the standalone datatype definition which is still available on the tool shed:

https://github.com/peterjc/galaxy_blast/blob/master/datatypes/blast_datatypes/blast.py#L22

From a visual inspection of the contents of the Excel file once unzipped into individual XML files, I struggle to understand how this could go wrong.

Could there be something off in the ``datatypes_conf.xml`` perhaps?

**Comment by peterjc** [comment]
Further more, even going back to the BLAST XML datatype when it was originally taken out of Galaxy, the essential BLAST XML sniffer logic has not changed:

https://github.com/peterjc/galaxy_blast/commit/7d82452706fa11dc89437e0015f14175cb98c106#diff-a32d54c60ab84531f6a6791591abffe5

i.e. Even some older version of the ToolShed definition from http://toolshed.g2.bx.psu.edu/view/devteam/blast_datatypes is installed, the logic ought never to recognise the Excel file.

**Comment by peterjc** [comment]
Uploading the test Excel file locally worked under Galaxy release_16.01, it was sniffed as format xlsx, peek text "uploaded xlsx file"

**Comment by mvdbeek** [comment]
Thanks @peterjc, this is not a blastxml issue and it is specific to usegalaxy.org. The major issue is the lack of `compressed = True` on the xlsx datatype, which is fixed by https://github.com/galaxyproject/galaxy/pull/6867 and was introduced with the dynamic compression framework in 18.05, I believe.

**Comment by mvdbeek** [comment]
I've set up some more advanced testing in https://github.com/galaxyproject/galaxy/pull/6869 and I don't see any issue with the blastxml datatype

**Comment by peterjc** [comment]
Progress, although I still fail to understand why BLAST XML is picked... but I will leave this in your capable hands. Thanks!

**Comment by mvdbeek** [comment]
Thanks, we'll try to figure this out!

**Comment by martenson** [comment]
Resolved by the above-linked PR.
