### ISSUE TITLE
Cannot upload files to an existing repo on either the TTS or the MTS

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#7974]
When using the Tool Shed UI to upload files to an existing repo, the following message is displayed on both the TTS and MTS.
```
The Tool Shed could not be reached

You are seeing this message because a request to The Tool Shed timed out or was refused. This may be a temporary issue which could be resolved by retrying the operation you were performing. If you receive this message repeatedly or for an extended amount of time, please contact an administrator.
```

**Comment by gregvonkuster** [comment]
This problem continues, even after the disk space issue was resolved yesterday.

On the TTS, I can now view a new empty repository which I own, but the Repository Actions menu is not displayed, so I canot upload any files.

On the MTS, clicking on the link to a new, empty repository that I own stil displays this error.
```
The Tool Shed could not be reached

You are seeing this message because a request to The Tool Shed timed out or was refused. This may be a temporary issue which could be resolved by retrying the operation you were performing. If you receive this message repeatedly or for an extended amount of time, please contact an administrator. 
```

**Comment by martenson** [comment]
I think there are two things here:
* some repos are in a bad state because they were created atm when we couldn't write to disk (so e.g. hgweb.config does not have an entry for it) 
* also we have another mount having space issues, I am not sure what it is used for but I see plenty of IO write errors in the log. I will see what I can do.

**Comment by gregvonkuster** [comment]
Thanks @martenson I created a new repo in both the TTS and MTS yesterday that are problematic.  They are both named affy2vcf2.  Maybe they can be used as examples for fixing.

**Comment by martenson** [comment]
@gregvonkuster both should be fixed now

**Comment by gregvonkuster** [comment]
Thanks @martenson On the TTS, I see that you added a changes.  I can now see the Repository Options menu and it has most of the options, but it is still missing the option to Upload files even though I am the owner.  Would it be better to just create another new repository named affy2vcf3 or something?

**Comment by martenson** [comment]
@gregvonkuster could you please try again with https://toolshed.g2.bx.psu.edu/view/greg/affy2vcf2/5e9d8a4f6ac8 ?

**Comment by gregvonkuster** [comment]
All is working now.  Thanks a bunch @martenson !

**Comment by martenson** [comment]
the cause was that the manualy initialized hg repos did not have propger hgrc file with your username in it
