### ISSUE TITLE
E-mail report error button broken

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8444]
Clicking the button just loads an empty page on dev.

Debug in the browser shows: `t.messages.forEach is not a function` and dataset-error.js:244

**Comment by bernt-matthias** [comment]
Maybe this is relevant, the relevant part of the log:

```
141.65.26.62 - - [15/Aug/2019:13:18:20 +0200] "GET /api/jobs/ad2ed0da9391fe09?full=True HTTP/1.1" 200 - "http://bioinf2-dev.eve.ufz.de:8080/datasets/error" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[pid: 18702|app: 0|req: 5615/11421] 141.65.26.62 () {42 vars in 792 bytes} [Thu Aug 15 13:18:20 2019] GET /api/jobs/ad2ed0da9391fe09?full=True => generated 3721 bytes in 92 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
141.65.26.62 - - [15/Aug/2019:13:18:20 +0200] "GET /api/jobs/ad2ed0da9391fe09/common_problems HTTP/1.1" 200 - "http://bioinf2-dev.eve.ufz.de:8080/datasets/error" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
[pid: 18702|app: 0|req: 5616/11422] 141.65.26.62 () {42 vars in 805 bytes} [Thu Aug 15 13:18:20 2019] GET /api/jobs/ad2ed0da9391fe09/common_problems => generated 68 bytes in 76 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)
[pid: 18702|app: -1|req: -1/11423] 141.65.26.62 () {36 vars in 679 bytes} [Thu Aug 15 13:18:23 2019] GET /static/scripts/bundled/analysis.bundled.js.map => generated 3958112 bytes in 3 msecs via offload() (HTTP/1.1 200) 2 headers in 90 bytes (0 switches on core 0)
[pid: 18702|app: -1|req: -1/11424] 141.65.26.62 () {40 vars in 753 bytes} [Thu Aug 15 13:18:23 2019] GET /static/scripts/bundled/libs.chunk.js.map => generated 0 bytes in 1 msecs (HTTP/1.1 304) 0 headers in 29 bytes (0 switches on core 3)
```

**Comment by dannon** [comment]
Thanks for the report here.  There's inconsistency right now between what the client expects and what is returned in the API response, but I'll have a fix out in a few.

**Comment by dannon** [comment]
This turned out to be more than just the inconsistency in the response, and should be fixed with https://github.com/galaxyproject/galaxy/pull/8702, I believe.

**Comment by bernt-matthias** [comment]
Just updated to the latest dev and the problem persists .. unfortunatelly.

**Comment by bernt-matthias** [comment]
According to my browser the error is from line `dataset-error.js:244:34`

**Comment by martenson** [comment]
This works fine for me on dev. Can you please try rebuilding the client (`$make client` in root) and refreshing `*.pyc`?

**Comment by bernt-matthias** [comment]
Did both without success.

**Comment by martenson** [comment]
@bernt-matthias is this with some extra bug reporting configuration, or just vanilla settings?

**Comment by bernt-matthias** [comment]
I'm not aware of extra bug reporting configs .. but maybe I forget something. Which config (files / options) do you think of?

**Comment by dannon** [comment]
@bernt-matthias Is this still an issue for you at this point?

**Comment by bernt-matthias** [comment]
No.
