### ISSUE TITLE
Workflow Text Overlap on small screen

### ISSUE THREAD

**Issue by juleengraham** [galaxyproject/galaxy#8491]
Some text on the workflow window overlaps when the browser window is too small. For example, see attached image.
<img width="375" alt="Screen Shot 2019-08-21 at 2 01 15 PM" src="https://user-images.githubusercontent.com/15222749/63456241-7d30f680-c41c-11e9-8c0d-3dbeb0ff1d78.png">

**Comment by bgruening** [comment]
@juleengraham any change you can test https://github.com/galaxyproject/galaxy/pull/8582

**Comment by guerler** [comment]
This has been fixed in the vue variant of the workflow list.

**Comment by bgruening** [comment]
@guerler will the new workflow list view be in 19.09 or should we still get this other PR into 19.09?

**Comment by dannon** [comment]
A year later, closing this out.   Confirmed that it works fine in modern releases.
